[2024-05-01T10:21:08.598+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T10:21:08.614+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-05-01T10:21:05.315844+00:00 [queued]>
[2024-05-01T10:21:08.620+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-05-01T10:21:05.315844+00:00 [queued]>
[2024-05-01T10:21:08.620+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-01T10:21:08.630+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): create_file_task> on 2024-05-01 10:21:05.315844+00:00
[2024-05-01T10:21:08.636+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T10:21:08.637+0000] {standard_task_runner.py:63} INFO - Started process 76 to run task
[2024-05-01T10:21:08.637+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'create_file_task', 'manual__2024-05-01T10:21:05.315844+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/Project.py', '--cfg-path', '/tmp/tmpxv00ad6m']
[2024-05-01T10:21:08.637+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask create_file_task
[2024-05-01T10:21:08.669+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.create_file_task manual__2024-05-01T10:21:05.315844+00:00 [running]> on host 73ada3aeb297
[2024-05-01T10:21:08.732+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='create_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T10:21:05.315844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T10:21:05.315844+00:00'
[2024-05-01T10:21:08.733+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T10:21:08.733+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T10:21:08.734+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch /opt/***/dags/database.db']
[2024-05-01T10:21:08.742+0000] {subprocess.py:86} INFO - Output:
[2024-05-01T10:21:08.745+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-01T10:21:08.745+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T10:21:08.764+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=create_file_task, execution_date=20240501T102105, start_date=20240501T102108, end_date=20240501T102108
[2024-05-01T10:21:08.811+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T10:21:08.830+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T10:21:08.831+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
