[2024-04-28T16:06:34.223+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T16:06:34.239+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-04-28T16:06:30.964075+00:00 [queued]>
[2024-04-28T16:06:34.244+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-04-28T16:06:30.964075+00:00 [queued]>
[2024-04-28T16:06:34.245+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-28T16:06:34.256+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): create_file_task> on 2024-04-28 16:06:30.964075+00:00
[2024-04-28T16:06:34.262+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T16:06:34.263+0000] {standard_task_runner.py:63} INFO - Started process 76 to run task
[2024-04-28T16:06:34.263+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'create_file_task', 'manual__2024-04-28T16:06:30.964075+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/Project.py', '--cfg-path', '/tmp/tmpn8o3das1']
[2024-04-28T16:06:34.264+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask create_file_task
[2024-04-28T16:06:34.303+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.create_file_task manual__2024-04-28T16:06:30.964075+00:00 [running]> on host 73ada3aeb297
[2024-04-28T16:06:34.369+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='create_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T16:06:30.964075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T16:06:30.964075+00:00'
[2024-04-28T16:06:34.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T16:06:34.371+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-28T16:06:34.372+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch /opt/***/dags/database.db']
[2024-04-28T16:06:34.380+0000] {subprocess.py:86} INFO - Output:
[2024-04-28T16:06:34.382+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-28T16:06:34.383+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T16:06:34.400+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=create_file_task, execution_date=20240428T160630, start_date=20240428T160634, end_date=20240428T160634
[2024-04-28T16:06:34.436+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T16:06:34.455+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T16:06:34.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
