[2024-04-28T15:54:34.261+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T15:54:34.277+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-04-28T15:54:31.319561+00:00 [queued]>
[2024-04-28T15:54:34.284+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.create_file_task manual__2024-04-28T15:54:31.319561+00:00 [queued]>
[2024-04-28T15:54:34.284+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-28T15:54:34.295+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): create_file_task> on 2024-04-28 15:54:31.319561+00:00
[2024-04-28T15:54:34.301+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T15:54:34.302+0000] {standard_task_runner.py:63} INFO - Started process 102 to run task
[2024-04-28T15:54:34.303+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'create_file_task', 'manual__2024-04-28T15:54:31.319561+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Project.py', '--cfg-path', '/tmp/tmptakv9y7z']
[2024-04-28T15:54:34.304+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask create_file_task
[2024-04-28T15:54:34.343+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.create_file_task manual__2024-04-28T15:54:31.319561+00:00 [running]> on host 73ada3aeb297
[2024-04-28T15:54:34.407+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='create_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T15:54:31.319561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T15:54:31.319561+00:00'
[2024-04-28T15:54:34.408+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T15:54:34.409+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-28T15:54:34.410+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch /opt/***/dags/database.db']
[2024-04-28T15:54:34.420+0000] {subprocess.py:86} INFO - Output:
[2024-04-28T15:54:34.422+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-28T15:54:34.422+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T15:54:34.441+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=create_file_task, execution_date=20240428T155431, start_date=20240428T155434, end_date=20240428T155434
[2024-04-28T15:54:34.476+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T15:54:34.496+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T15:54:34.497+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
