[2024-04-28T15:54:32.719+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T15:54:32.735+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Final_exam.starting manual__2024-04-28T15:54:31.319561+00:00 [queued]>
[2024-04-28T15:54:32.742+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Final_exam.starting manual__2024-04-28T15:54:31.319561+00:00 [queued]>
[2024-04-28T15:54:32.742+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-28T15:54:32.759+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): starting> on 2024-04-28 15:54:31.319561+00:00
[2024-04-28T15:54:32.766+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T15:54:32.767+0000] {standard_task_runner.py:63} INFO - Started process 93 to run task
[2024-04-28T15:54:32.767+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Final_exam', 'starting', 'manual__2024-04-28T15:54:31.319561+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/Project.py', '--cfg-path', '/tmp/tmpeeg93v1k']
[2024-04-28T15:54:32.768+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask starting
[2024-04-28T15:54:32.804+0000] {task_command.py:426} INFO - Running <TaskInstance: Final_exam.starting manual__2024-04-28T15:54:31.319561+00:00 [running]> on host 73ada3aeb297
[2024-04-28T15:54:32.868+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ha20040204@gmail.com' AIRFLOW_CTX_DAG_OWNER='HA' AIRFLOW_CTX_DAG_ID='Final_exam' AIRFLOW_CTX_TASK_ID='starting' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T15:54:31.319561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T15:54:31.319561+00:00'
[2024-04-28T15:54:32.869+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T15:54:32.870+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-28T15:54:32.871+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Chuẩn bị cào dữ liệu"']
[2024-04-28T15:54:32.881+0000] {subprocess.py:86} INFO - Output:
[2024-04-28T15:54:32.883+0000] {subprocess.py:93} INFO - Chuẩn bị cào dữ liệu
[2024-04-28T15:54:32.883+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-28T15:54:32.883+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T15:54:32.904+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Final_exam, task_id=starting, execution_date=20240428T155431, start_date=20240428T155432, end_date=20240428T155432
[2024-04-28T15:54:32.940+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T15:54:32.962+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-04-28T15:54:32.964+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
